---
- hosts: all
  name: Terraform Slave playbook
  remote_user: ubuntu
  gather_facts: false
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Java 11
      package:
        name: openjdk-11-jdk
        state: present

    - name: Install Terraform
      snap:
        name: terraform
        classic: yes
        state: present
        channel: latest
